### ISSUE TITLE
kwik as client side connect to https://github.com/cloudflare/quiche fail

### ISSUE THREAD

**Issue by xtuyaowu** [ptrd/kwik#21]
hi guys 
    kwik as client side connect to https://github.com/cloudflare/quiche fail ：Handshake error 

    Whether with or without a certificate

thanks！

**Comment by ptrd** [comment]
Can you elaborate a bit more on exactly what you tried?
https://github.com/cloudflare/quiche does not support HTTP3, so that one is easy explained.
But maybe you this not what you meant, in that case it would help a lot if you describe the problem somewhat better.

**Comment by xtuyaowu** [comment]
@ptrd hi Peter
    try use kwik as quic client connect to rust quic server got error
   ome/bin/java -XX:+ShowCodeDetailsInExceptionMessages @/var/folders/bx/6qwh8m5x5l10l58lt85hrxfr0000gn/T/cp_8o2xo84mxwz5xiltp89255vct.argfile com.QuicClient
Exception in thread "main" java.net.ConnectException: Handshake error
        at net.luminis.quic.QuicClientConnectionImpl.connect(QuicClientConnectionImpl.java:226)
        at net.luminis.quic.QuicClientConnectionImpl.connect(QuicClientConnectionImpl.java:167)
        at com.QuicClient.main(QuicClient.java:30)

Can you give some idea what the problem is ,can both client and server side ignore certificate check ？

thanks

**Comment by ptrd** [comment]
Did you instruct kwik to skip certificate check?
What is kwik client log output? Please enable error logging and packet logging (if you use KwikCli class this is the default setting).

**Comment by xtuyaowu** [comment]
[8:46](https://wmjtyd.slack.com/archives/D03K0HA59UG/p1657197984644619)
        QuicClientConnectionImpl connection =
                builder.version(Version.QUIC_version_1)
                        .uri(new URI("https://127.0.0.1:4433/"))


44:51.231 Creating connection with 127.0.0.1:4433 with QUIC_version_1
44:51.284 Original destination connection id: 43e8a7db26079428 (scid: e0b2016fd2ebec3a)
          >- CryptoStream[I|ClientHello]
44:51.341 <- (1) Packet I|-|R|69| Retry Token (18): 7175696368657f00000143e8a7db26079428
          >- CryptoStream[I|ClientHello,ClientHello]
44:51.341 -> Packet I|0|L|1200|2  Token=[] CryptoFrame[0,241] Padding(912)
44:51.353 -> Packet I|1|L|1200|2  Token=7175696368657f00000143e8a7db26079428 CryptoFrame[0,241] Padding(882)
44:52.363 -> Packet PI|2|L|1230|2  Token=7175696368657f00000143e8a7db26079428 CryptoFrame[0,241] Padding(912)
44:52.363 <- (2) Packet I|0|L|60|1  Token=[] ConnectionCloseFrame[TLS 50|0|]
44:52.370 Error: Connection closed by peer with TLS error 50: 
44:52.373 Error: Inconsistency error in congestion controller; attempt to set bytes in-flight below 0
44:52.379 -> Packet I|3|L|1201|3  Token=7175696368657f00000143e8a7db26079428 ConnectionCloseFrame[0|0|] AckFrame[0|Δ0] Padding(1119)
Exception in thread "main" java.net.ConnectException: Handshake error
        at net.luminis.quic.QuicClientConnectionImpl.connect(QuicClientConnectionImpl.java:226)
        at net.luminis.quic.QuicClientConnectionImpl.connect(QuicClientConnectionImpl.java:167)
        at com.wmjtyd.QuicClient.main(QuicClient.java:72)
                        .logger(log)
                        .noServerCertificateCheck()
                        .build();

**Comment by ptrd** [comment]
I cannot reproduce it. Running quiche server locally, connecting with kwik client, works like charm.

**Comment by xtuyaowu** [comment]
can you give me the command or code ？

**Comment by ptrd** [comment]
LOL. I think the normal procedure one someone reports a bug, it that the reporter shows what (s)he has done, so the developer can easily reproduce the scenario. You want to read this: http://www.catb.org/~esr/faqs/smart-questions.html

I simply ran quiche server as indicated in the quiche readme. I simply connected with kwik client as explained in the kwik readme.

Please don't waste my time. I will help you, but in return, you should help me by making as clear as possible what you are doing.

**Comment by ptrd** [comment]
ALPN is missing, can't be empty.

**Comment by ptrd** [comment]
fixed: https://github.com/ptrd/kwik/commit/efb4a799f000cf5d9a258566d87f73dbac31334a

**Comment by xtuyaowu** [comment]
still have problem after add hq-interop got error
servername does not match
agent15/src/net/luminis/tls/handshake/TlsClientEngine.java : 327
